### ISSUE TITLE
pbkdf2 code is outdated

### ISSUE THREAD

**Issue by grondilu** [petjal/bitcoin-bash-tools#11]
The code you included for pbkdf2 has been corrected in this commit : https://github.com/grondilu/bitcoin-bash-tools/commit/5eeff3844a2f429157c4f854c389d0583bb72d44

The code you use works for this particular application but cannot be generalized for other key sizes.

**Comment by petjal** [comment]
I believe this is fixed in https://github.com/petjal/bitcoin-bash-tools/commit/4c8338e12d4c1acff97db9c8d9969aaeac77c109
Thank you very much, grondilu!
